### ISSUE TITLE
Tkinter is now required for version 0.4.3 after patching the turtle code

### ISSUE THREAD

**Issue by reneeotten** [spyder-ide/spyder-kernels#102]
With the merge of PR #90, Python now needs "to be configured for Tk" due to the explicit import of ```turtle``` (which in turn does ``` import Tkinter as TK```). I was updating ```py-spyder``` to version 3.3.4 in MacPorts and because of this I would need to add a dependency on ```py-tkinter```, which recursively pulls in ```tk```, ```tcl``` and their dependencies. We didn't do that before and whereas (admittedly) the same error would appear if someone selected the ```Tkinter``` backend, everything would work fine for the (default) "inline" or the "Qt5" backends.

I couldn't find the need of "having Python configured for Tk" in the requirements for spyder or spyder-kernels, did I miss this somewhere? I also suppose that the patching of the ```turtle``` code would only be relevant when choosing the Tkinter graphical backend and not for others - correct? If so, would it be possible to only do this when selecting the Tkinter backend? 

I'd appreciate your comments/suggestions and would welcome any advice you can give (regarding dependencies / backends) for downstream packagers.

**Comment by ccordoba12** [comment]
Thanks for reporting. We didn't know Python can be installed without Tk (we assumed that Tk was a Python runtime dependency due to IDLE and turtle).

However, this is an easy fix: instead of unconditionally importing `turtle` in our customize file, we can simply enclose the code added in #90 in a try/except.

I'll do that right away to release 0.4.5.

**Comment by ccordoba12** [comment]
I think that's enough, right? Please see #103 and let me know if that works for you (we do the same thing for Pandas, Matplotlib, etc to not add a hard dependency on them).

**Comment by sebix** [comment]
The tk-dependency of the tests is nowhere mentioned (not in the setup's requirements and not in the changelog)

**Comment by ccordoba12** [comment]
We use Anaconda to test almost all our packages and the Python package provided by it comes with Tk as a runtime dependency. However, we can skip the test if Tk is not found.
