### ISSUE TITLE
test_output_from_c_libraries fails on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by sebix** [spyder-ide/spyder-kernels#105]
During packaging I have the test `test_output_from_c_libraries` failing:

```
________________________________________________________________ test_output_from_c_libraries ________________________________________________________________

kernel = <spyder_kernels.console.kernel.SpyderKernel object at 0x7effe0308128>, capsys = <_pytest.capture.CaptureFixture object at 0x7effe03086a0>

    @pytest.mark.skipif(os.name == 'nt', reason="Doesn't work on Windows")
    def test_output_from_c_libraries(kernel, capsys):
        """Test that the wurlitzer extension is working."""
        # This code was taken from the Wurlitzer demo
        code = """
    import ctypes
    libc = ctypes.CDLL(None)
    libc.printf(('Hello from C\\n').encode('utf8'))
    """
    
        # Without Wurlitzer there's not output generated
        # by the kernel
        reply = kernel.do_execute(code, True)
        captured = capsys.readouterr()
        assert captured.out == ''
    
        # With Wurlitzer we have the expected output
        kernel._load_wurlitzer()
        reply = kernel.do_execute(code, True)
        captured = capsys.readouterr()
>       assert captured.out == "Hello from C\n"
E       AssertionError: assert '' == 'Hello from C\n'
E         + Hello from C

spyder_kernels/console/tests/test_console_kernel.py:307: AssertionError
```

Do you know how I can solve that?

**Comment by ccordoba12** [comment]
This is not enough because it doesn't tell us what's happening. It works in our local tests though.

**Comment by ccordoba12** [comment]
I meant when we run our tests in Travis (macOS) and Circle (Linux).

**Comment by jitseniesen** [comment]
This test fails if the wurlitzer extension could not be loaded, so that's where I'd start looking.

**Comment by ccordoba12** [comment]
Well, that's a requirement since we introduced that functionality.

I'm closing this because it's really not our responsibility. If you want to run our tests in your infrastructure (even if we don't package them anymore), it's your choice. But those tests are working here, so you need to find what's different in your CI environment, compared to Travis and Circle.

**Comment by sebix** [comment]
> This test fails if the wurlitzer extension could not be loaded, so that's where I'd start looking.

Shouldn't the test fail with another error message then? E.g. an ImportError?

**Comment by ccordoba12** [comment]
No, because wurlitzer is a dependency of this package:

https://github.com/spyder-ide/spyder-kernels/blob/master/setup.py#L56
