### ISSUE TITLE
Set matplotlib backend to inline by default on starting a new kernel

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-kernels#108]
Opened by request of @ccordoba12 

``spyder-kernels`` should set the graphics backend to ``inline`` by default on starting a ``spyder-kernels`` kernel, to match the Spyder default and so plots work by default on remote machines over ``ssh``. Currently, in my testing, plots in such consoles appear in interactive mode (i.e. Qt backend), rather than inline.

**Comment by ccordoba12** [comment]
PR #110 should take care of this, please test it. However, you have to be aware that if a kernel is started by Spyder in an external interpreter, then that kernel will be configured using our Preferences system.

**Comment by CAM-Gerlach** [comment]
> PR #110 should take care of this, please test it.

Sure, thanks! See my comments there.

> However, you have to be aware that if a kernel is started by Spyder in an external interpreter, then that kernel will be configured using our Preferences system.

Yup, that's expected.
