### ISSUE TITLE
tests use removed pandas.Panel

### ISSUE THREAD

**Issue by sebix** [spyder-ide/spyder-kernels#132]
Pandas 0.25 has removed Panels: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html
> Warning: Panel has been fully removed. For N-D labeled data structures, please use xarray 

It is used here:
https://github.com/spyder-ide/spyder-kernels/blob/f281e8ead6c1d1414ad4050dd78a112a3b45fb96/spyder_kernels/utils/tests/test_nsview.py#L38

Pandas 0.25.0 has been released on July 18th.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is only used in our tests, so it doesn't represent any problem to our users.

Besides, our tests are not distributed in our tarballs and wheels, so that makes it an even a smaller issue.

**Comment by sebix** [comment]
Thanks for the fix!
