### ISSUE TITLE
Regression: runfile doesn't execute ipython magic

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder-kernels#139]
`ipython_shell.run_cell` was replaced by a straight call to `exec` in runcell, which means that the ipython magic are not executed anymore. The main raison for this change is that calling `exec` allows to correctly set the filename which:

 1. Allows Pdb to correctly set breakpoints. Otherwise it has no way of knowing the file the cell is in.
 2. Creates correct tracebacks when an exception is raised.

To restore this behaviour, `ipython_shell.run_cell` needs to be modified upstream. More specifically, `async def run_cell_async` needs to have an extra `file_name` argument to replace `cell_name`. The question that remain is: Do we want to support calling magic in `runfile` as well? This can be done by loading the file (`with open(...) as f:`) and using its content as a single cell. I don't think runfile and runcell should behave differently.

**Comment by impact27** [comment]
From @bcolsen in #134 :

> So should runfile also accept magic?

The IPython %run magic only allows magics in .ipy and .ipynb they just run all the cells in a notebook file or the whole file in the case of an .ipy file. We could support .ipy file with spyder style cells or try to upstream that idea to IPython. We could also just have a button in spyder to run all the cells.

https://github.com/ipython/ipython/blob/8971c8e5f31d20768609e20f60870d627eb33bd0/IPython/core/interactiveshell.py#L2741

It looks like they also can't get the file name for the trace backs but give a little warning at the end saying file they were running when the errors happened.

If we have to make a choice between having magics(I think IPython run_cell also does some async stuff and module reloads) or having filenames in tracebacks, I would pick magics and the stability of IPython run_cell(my opinion).

In general IPython functions get a lot of testing and we should use then when we can. I know that this is working around problem with the debugger, but the closer we stay to upstream then the lighter the bug fixing load there is here. There are only so many corner cases we can test.

**Comment by impact27** [comment]
> If we have to make a choice between having magics(I think IPython run_cell also does some async stuff and module reloads) or having filenames in tracebacks, I would pick magics and the stability of IPython run_cell(my opinion).

For me the main point of using `exec` is that Pdb breakpoints work. And the stability of `exec` is not really lesser than the stability of `IPython run_cell`. I think that we can probably have both but I would choose a working Pdb over having magics. I mean magics are not really supposed to be in `.py` files anyway.

**Comment by ccordoba12** [comment]
> One other regression here is that the "results" (usually the the out put of the last line of the cell) will also not be displayed.

I agree it'd be really nice to have this back.

**Comment by ccordoba12** [comment]
> Another regression: Runcell now saves the file

This can be easily reverted, at least by passing a parameter to `runcell` that controls when to save the file and setting it to False by default.

@impact27?

**Comment by impact27** [comment]
> Another regression: The new runcell saves the file before execution.

We can trivially disable the save before execution for runcell. But if runfile saves the file before execution, shouldn't runcell do the same? Or should that be disabled for both runfile and runcell?

**Comment by impact27** [comment]
Also, if you don't save the file, the cell will still run.

**Comment by impact27** [comment]
The solution for runfile couls be to implement a code fetching feature similar to runcell, instead of reading the file from disk.

**Comment by impact27** [comment]
> and will make running cells from a queue more difficult spyder-ide/spyder#9725.

Why? Do you want to let the user run a cell and then modify it while it is in the queue? This will already be difficult, as the code is fetched at execution time.

**Comment by impact27** [comment]
> One other regression here is that the "results" (usually the the out put of the last line of the cell) will also not be displayed.

Is that something you would expect from python code? If I write a script, I wouldn't want something to print unless I write `print(`. Obviously this would be different for `.ipy` files.

**Comment by ccordoba12** [comment]
> We can trivially disable the save before execution for runcell. But if runfile saves the file before execution, shouldn't runcell do the same? Or should that be disabled for both runfile and runcell?

I think the main difference is that `runfile` is used to check if your entire file is running as expected, whereas `runcell` is more for quick, interactive work.

The main UI problem I see between allowing to run a cell with or without saving its file is where you want to run that cell from:

1. If you're runming it from the editor, then you probably don't need to save the file all the time because you're constantly iterating and making progress along the way (I think this is @bcolsen's point of view).
2. If you call `runcell` from the console, then you really need to ask the editor to save your changes, else it won't be able to run it correctly (this is clearly @impact27's point of view).

Since there's no single way to cover both use cases, I think adding an option to specify if the user wants to save the file before `runcell` is in order. But I'm unsure where to add it and what its default value should be.

**Comment by impact27** [comment]
> 2. If you call runcell from the console, then you really need to ask the editor to save your changes, else it won't be able to run it correctly (this is clearly @impact27's point of view).

It will run correctly even if you don't save the file. The objection I have is more about having different behaviour between runcell and runfile. The "runfile without saving" is what was asked in https://github.com/spyder-ide/spyder/issues/7760. But I don't feel strongly about this. 

It can be done by removing https://github.com/spyder-ide/spyder/blob/08f04cfb50cfb74e8120e8ac91f2f5e510999b5a/spyder/plugins/ipythonconsole/widgets/shell.py#L495 and https://github.com/spyder-ide/spyder/blob/08f04cfb50cfb74e8120e8ac91f2f5e510999b5a/spyder/plugins/ipythonconsole/widgets/shell.py#L510

**Comment by impact27** [comment]
I thought about it, and I think the main argument I have for saving the files before `runfile` and `runcell` is the following: The code in that runs in this file might run code in other files. Therefore, to run the code as it is open in the editor, you need to save all the modified files. I would therefore propose:

 - Calling `UserModuleReloader.run()` in runcell.

 - Changing the saving behaviour from "Save all files." to "Save modified files but not new files.". This will allow the modified code to run properly without saving eventual `untitled*.py` files, therefore solving spyder-ide/spyder#7760. Also this means no pop-up.

 - Getting the code for `runfile` from the editor, in a similar was as `runcell` does. This will allow running new files without saving them (also spyder-ide/spyder#7760). If the file is modified, it will still be saved.

**Comment by ccordoba12** [comment]
Thanks @impact27 for giving more thought to this. Your proposal sounds reasonable to me.

@bcolsen?

**Comment by jitseniesen** [comment]
Just to be clear, this is only about runcell function when run from the console, the behaviour of the "Run Cell" menu and toolbox items will not change from what it was in Spyder 3?

**Comment by impact27** [comment]
> Just to be clear, this is only about runcell function when run from the console, the behaviour of the "Run Cell" menu and toolbox items will not change from what it was in Spyder 3?

There is no difference between running from the console and from the toolbox items

**Comment by jitseniesen** [comment]
So we are talking about changing behaviour then: in Spyder 3, files did not save when pressing "Run cell", while after the change, all files (except new files) will save.

> I thought about it, and I think the main argument I have for saving the files before `runfile` and `runcell` is the following: The code that runs in this file might run code in other files. Therefore, to run the code as it is open in the editor, you need to save all the modified files.

I am not convinced this is enough justification to change existing behaviour and save possibly unrelated files to disk. When you do "Run cell", the code being run does not reflect anything going on in other parts of the same file, so you are in a bit of a confusing situation already. Users should perhaps not expect "Run cell" to run the code as it is open in the editor. 

I sympathize with your argument that "Run file" and "Run cell" should behave similarly, but then what about "Run line"? By the same argument, that should also save all files.

Actually, I don't know what I prefer. I am just a bit surprised that @ccordoba12 seemed to have changed his opinion so rapidly from "there needs to be an option whether the user wants to save files" to "always save files" and I am wondering whether he realized that the extent of what you are proposing, as this was not clear to me.

**Comment by bcolsen** [comment]
>     * Calling `UserModuleReloader.run()` in runcell?

I've done some testing of this already and it seems that if the module is imported in the cell code it uses the changed module. This would be a good reason to save all the files.

Also if the UMR for a cell could look for and reload imports, classes and functions that are defined in else where in the script's top level namespace that would be a game changer. If we had this and interactive plots in debugging I might use classes and functions more often.

>     * Changing the saving behaviour from "Save all files." to "Save modified files but not new files.". This will allow the modified code to run properly without saving eventual `untitled*.py` files, therefore solving [spyder-ide/spyder#7760](https://github.com/spyder-ide/spyder/issues/7760). Also this means no pop-up.

I think this would solve most complaints about saving all the file and is a great idea. Having to save that new file at some random place just to runcell is annoying

>     * Getting the code for `runfile` from the editor, in a similar was as `runcell` does. This will allow running new files without saving them (also [spyder-ide/spyder#7760](https://github.com/spyder-ide/spyder/issues/7760)). If the file is modified, it will still be saved.

Also nice, but what filename will you give to execute and how will you get the tracebacks since tracebacks are taken from the file not the code? I think that this is one reason why IPython run_cell does code caching and execution hashes instead of file names.

**Comment by impact27** [comment]
> Also nice, but what filename will you give to execute and how will you get the tracebacks since tracebacks are taken from the file not the code? I think that this is one reason why IPython run_cell does code caching and execution hashes instead of file names.
> 
The file name would be whatever the editor thinks the filename is. If you create a new file, this filename is "cwd + untitled0.py", even if this file doesn't actually exist. The tracebacks are not taken from the file, they are taken from the code you give to exec, which is loaded from the file. It could be loaded from the editor instead. This is why runcell has correct tracebacks even though the file doesn't need to exist.

**Comment by bcolsen** [comment]
It seems that only the line numbers are recorded in the traceback and then the code line are taken from the file after execution. https://stackoverflow.com/a/33175832

You can try it yourself like this:

Run this code and with in 10 seconds put a newline after `sleep(10)`.
```python
# %% first
from time import sleep
sleep(10)
print('neat')  # not an error
print(yo)  # I'm an error
```

The error will look like this:

``` python traceback
In [1]: runcell('first', '/home/bcolsen/Documents/ipy_test.py')
neat
Traceback (most recent call last):

  File "/home/bcolsen/Documents/ipy_test.py", line 13, in <module>
    print('neat')  # not an error

NameError: name 'yo' is not defined
```

This is just a python thing and it happens even in the python executable, but it wouldn't happen from IPython run_cell hashed code cache. However, it's nice having the filename and not a hash. This also affects postmortem debugging because it uses the traceback. This is really a python bug. It would be nice if python at least had a option to cache the source code of at least the main script when compiling instead of relying on the file itself.

If you use `compile` with a file that doesn't exist and `exec` it. The code does run but in the traceback there are just no line snippits, only line numbers, which is probably fine. I can't get postmortem debugging to work in this case, but there are no errors.

**Comment by impact27** [comment]
> It seems that only the line numbers are recorded in the traceback and then the code line are taken from the file after execution. https://stackoverflow.com/a/33175832 <https://stackoverflow.com/a/33175832>
> You can try it yourself like this:
> 
> Run this code and with in 10 seconds put a newline after sleep(10).
> 
> # %% first
> from time import sleep
> sleep(10)
> print('neat')  # not an error
> print(yo)  # I'm an error
> The error will look like this:
> 
> In [1]: runcell('first', '/home/bcolsen/Documents/ipy_test.py')
> neat
> Traceback (most recent call last):
> 
>   File "/home/bcolsen/Documents/ipy_test.py", line 13, in <module>
>     print('neat')  # not an error
> 
> NameError: name 'yo' is not defined
> This is just a python thing and it happens even in the python executable, but it wouldn't happen from IPython run_cell hashed code cache. However, it's nice having the filename and not a hash. This also affects postmortem debugging because it uses the traceback. This is really a python bug. It would be nice if python at least had a option to cache the source code of at least the main script when compiling instead of relying on the file itself.
> 
> If you use compile with a file that doesn't exist and exec it. The code does run but in the traceback there are just no line snippits, only line numbers, which is probably fine. I can't get postmortem debugging to work in this case, but there are no errors.
> 

You are right, there is no line snippets. The postmortem debugging does work for me, but I can't use `list`. Does that mean that to debug correctly, the file needs to be saved?

**Comment by impact27** [comment]
For tracebacks, you can add the code to linecache for it to show.

**Comment by impact27** [comment]
```python
filename = '/non/existing/file.py'
data = '''
def fun():
    test = 12
    raise RuntimeError('WHat')
fun()
'''
import linecache
linecache.cache[filename] = (
                    len(data), None,
                    [line+'\n' for line in data.splitlines()], filename
                )
exec(compile(data, filename, 'exec'))
```
<img width="702" alt="Screenshot 2019-08-30 at 06 43 05" src="https://user-images.githubusercontent.com/6740194/63995901-fd78eb00-caf1-11e9-8578-3afa945f034d.png">

**Comment by impact27** [comment]
The only problem is that this is not really a documented way to use linecache. I wonder if https://www.python.org/dev/peps/pep-0302/ `__loader__` would be a better approach.

**Comment by impact27** [comment]
The debugging works as well:
<img width="691" alt="Screenshot 2019-08-30 at 07 45 39" src="https://user-images.githubusercontent.com/6740194/63998938-3917b300-cafa-11e9-992e-4778bb3c47f0.png">

**Comment by bcolsen** [comment]
>The postmortem debugging does work for me, but I can't use `list`. Does that mean that to debug correctly, the file needs to be saved?

It actually seem to debug fine it just doesn't have the lines to display which makes it hard to tell that it's working.

That `linecache` trick works great. With that I can even debug a "file" that has the same filename as another. I think we should linecache all the code by default to solve the "line are taken from the file after execution". 
```python
import linecache

filename = '/home/bcolsen/Documents/ipy_test.py'
data = '''
def fun():
    a = 10
    print(yo)
test = 12
fun()
'''
# linecache.cache[filename] = (
#         len(data), None,
#         data.splitlines(keepends=True), filename)
exec(compile(data, filename, 'exec'))
Traceback (most recent call last):

  File "<ipython-input-1-f4fdd0090385>", line 14, in <module>
    exec(compile(data, filename, 'exec'))

  File "/home/bcolsen/Documents/ipy_test.py", line 6, in <module>
    @author: bcolsen

  File "/home/bcolsen/Documents/ipy_test.py", line 4, in fun
    Created on Mon Aug 26 16:44:44 2019

NameError: name 'yo' is not defined

```
vs
```python

import linecache

filename = '/home/bcolsen/Documents/ipy_test.py'
data = '''
def fun():
    a = 10
    print(yo)
test = 12
fun()
'''
linecache.cache[filename] = (
        len(data), None,
        data.splitlines(keepends=True), filename)
exec(compile(data, filename, 'exec'))
Traceback (most recent call last):

  File "<ipython-input-2-3c70af193f2d>", line 14, in <module>
    exec(compile(data, filename, 'exec'))

  File "/home/bcolsen/Documents/ipy_test.py", line 6, in <module>
    fun()

  File "/home/bcolsen/Documents/ipy_test.py", line 4, in fun
    print(yo)

NameError: name 'yo' is not defined
```

The linecache might need to be cleared after execution.

**Comment by bcolsen** [comment]
Linecache plus the "don't save new files" idea clears the problems I have with saving and caching aswell as  fixes spyder-ide/spyder#7760

**Comment by impact27** [comment]
I am implementing this in #143

**Comment by impact27** [comment]
I am not sure if I should use `data.splitlines(keepends=True)` or `[line+'\n' for line in data.splitlines()]`, as the latter is what `linecache` does.

**Comment by bcolsen** [comment]
I would assume keepends would be implemented in c and would be faster than a python loop

**Comment by impact27** [comment]
I wonder if linecache would be expecting a ‘\n’ even on windows.

**Comment by bcolsen** [comment]
> I wonder if linecache would be expecting a ‘\n’ even on windows.

You can use linecache.getline on a windows txt file and see if it gives you `/n` at the end of the line or whatever windows newlines are. I suspect it will be the windows one.

**Comment by impact27** [comment]
I don’t have access to a window machine, could someone have a look?

**Comment by bcolsen** [comment]
You can change the line endings in Spyder using the source menu. 

I tried it and the line endings are changed to `/n` by linecache.

Hopefully the loop won't be too slow on large source files.

**Comment by bcolsen** [comment]
Potentially associated Spyder issue https://github.com/spyder-ide/spyder/issues/1643

**Comment by impact27** [comment]
I think the solution for ipython magic is to use `IPython.core.inputtransformer2` to transform the magic into valid python code.

**Comment by impact27** [comment]
```
from IPython.core.inputtransformer2 import TransformerManager
tm = TransformerManager()
tm.cleanup_transforms = []
tm.transform_cell('\n\n# comment\n\n%matplotlib qt5\n\na = %foo\n')
```
Out:
```
"\n\n# comment\n\nget_ipython().run_line_magic('matplotlib', 'qt5')\n\na = get_ipython().run_line_magic('foo', '')\n"
```

**Comment by impact27** [comment]
I'll add that to #143
