### ISSUE TITLE
Startup lines to split with semicolon instead of comma

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder-kernels#14]
## Issue
Currently I can't use a IPyhton startup lines like these in Sypder since the line is parsed with comma separation:

```python
from modual import func1, func2
```
or 
```python
import os, sys
```

These common python import structures don't work in startup lines. I actually thought it was broken until I read the note in the ipython config and thought about the implications of using comma separation.

## Solution

If we use semicolon to separate the lines like you can do in python then any valid python should be possible.

Then you could use:
```python
import os, sys; from modal import func1, func2
```

The fix could be as simple as changing this comma to a semicolon in this code, or the line could be executed directly since it is valid python.
 
https://github.com/spyder-ide/spyder-kernels/blob/9a49376ec01ad41af5d3522758e5b4bb30ce85a8/spyder_kernels/console/start.py#L102-L106

## Potential Problem

This is a compatibility concern since the startup lines from 3 would not work in 4, but it's a good time to make a braking change or we can tell that a config file is from 3 it can be upgraded to 4 by replacing the commas with semicolons automatically.

**Comment by ccordoba12** [comment]
> This is a compatibility concern since the startup lines from 3 would not work in 4, but it's a good time to make a braking change or we can tell that a config file is from 3 it can be upgraded to 4 by replacing the commas with semicolons automatically.

I agree, let's change to use semicolons and replace commas with semicolons to try to preserve compatibility with Spyder 3.

**Comment by bcolsen** [comment]
This will be a bit of work on Python 2 since ConfigParser on 2 sees `;` as a comment.

https://bugs.python.org/issue16374

Python 3 has rewritten ConfigParser and works without issue.

There is a backport of the 3 version for 2 here:

https://pypi.org/project/configparser/
