### ISSUE TITLE
KeyError on comms when restarting the kernel

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-kernels#145]
After pressing `Ctrl+.` or going to the menu `Consoles > Restart kernel`, I'm seeing the following error in the console:

```python-traceback
 Exception ignored in: <bound method Comm.__del__ of <ipykernel.comm.comm.Comm object at 0x7f11104c6b70>>
Traceback (most recent call last):
  File "/home/carlos/miniconda/envs/py36/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 76, in __del__
    self.close()
  File "/home/carlos/miniconda/envs/py36/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 116, in close
    self.kernel.comm_manager.unregister_comm(self)
  File "/home/carlos/miniconda/envs/py36/lib/python3.6/site-packages/ipykernel/comm/manager.py", line 56, in unregister_comm
    comm = self.comms.pop(comm.comm_id)
KeyError: ('99d1e7ecd6e411e9a618730903f71102',)
```

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this one this weekend? Sorry to ask you that but I noticed that yesterday and I'd like to release beta5 tomorrow with a fix for this.

**Comment by impact27** [comment]
I don't wee how this code could ever be run without raising an error. If the function `__del__` is called, the comm is necessary not in any dictionary (The refcount is at 0). So there is no way for the comm manager to remove it from the list. This has to be fixed in ipykernel. On the other hand, this is not actually important, and we can just clear the console when the kernel finishes loading to clear any error messages.

**Comment by impact27** [comment]
https://github.com/jupyter/qtconsole/pull/376

**Comment by impact27** [comment]
These two pull requests should solve this problem.

**Comment by ccordoba12** [comment]
> These two pull requests

What's the other PR?

**Comment by impact27** [comment]
https://github.com/ipython/ipykernel/pull/433

**Comment by impact27** [comment]
I mean ipython/ipykernel#433 will solve this problem specifically, and jupyter/qtconsole#376 removes the `WARNING:traitlets:No such comm: 23e9952ad6ee11e98294784f4365644a` messages from the internal console.

**Comment by ccordoba12** [comment]
I have a temporal solution for beta5 because I don't know when the `ipykernel` PR is going to be merged, much less when it's going to be part of a new release.

We could override `_comm_close` in `FrontendComm` like this

```python
def _comm_close(self, msg):
    """Close comm."""
    comm_id = msg['content']['comm_id']
    comm = self._comms[comm_id]

    self.kernel.comm_manager.unregister_comm[comm]
    del self._comms[comm_id]
```

Do you agree?

**Comment by impact27** [comment]
I am not sure if this would work. I would probably just monkeypatch the `__del__` function of  `ipykernel/comm/comm` to do nothing. I am not sure this needs to be done as this doesn't break anything, this just adds a bit of text to the console. The console could be cleared after the kernel restarts.

**Comment by ccordoba12** [comment]
> I am not sure if this would work

I tried it already and it works.

> The console could be cleared after the kernel restarts.

That's harder to do than you think without evaluating code in the kernel. Besides, this is just a temporary fix until we can rely on a new version of ipykernel.

**Comment by impact27** [comment]
What about:
```
     def _comm_close(self, msg):
        """Close comm."""
        comm_id = msg['content']['comm_id']
        comm = self._comms[comm_id]
        # Pretend it is already closed to avoid problems when closing
        comm._closed = True
        del self._comms[comm_id]
```
In your solution, the error is still raised but the console is cleaned after the error is printed.
