### ISSUE TITLE
spydercustomize.runfile seems to be wrong version

### ISSUE THREAD

**Issue by colinww** [spyder-ide/spyder-kernels#184]
Just installed Spyder 4.
## Versions

* Spyder version: 4.0.0rc2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

When I run a script, I get this error:

```
Python 3.7.5 (default, Oct 25 2019, 10:52:18)
Type "copyright", "credits" or "license" for more information.

IPython 7.9.0 -- An enhanced Interactive Python.

runfile('/Users/colinww/system-model/work/fft_block_lms_noise_analysis.py', wdir='/Users/colinww/system-model/work', current_namespace=True)
Traceback (most recent call last):

  File "<ipython-input-1-73b5de20005a>", line 1, in <module>
    runfile('/Users/colinww/system-model/work/fft_block_lms_noise_analysis.py', wdir='/Users/colinww/system-model/work', current_namespace=True)

TypeError: runfile() got an unexpected keyword argument 'current_namespace'
```

Looking in the file `/Users/colinww/anaconda3/pkgs/spyder-kernels-1.8.0-py37_0/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py` shows the following:
```
def runfile(filename=None, args=None, wdir=None, namespace=None,
            post_mortem=False, current_namespace=False):
```
But,
```
runfile
Out[11]: <function spydercustomize.runfile(filename, args=None, wdir=None, namespace=None, post_mortem=False)>
```
So I'm trying to figure out from where Spyder is pulling this function definition (or what's wrong with my env to result in this behavior). I configured my spyder environment like this:
```
$ conda create --channel spyder-ide --name spyder-beta spyder=4.0.0rc2
$ conda activate spyder-beta
$ spyder
```
Thank you.

**Comment by ccordoba12** [comment]
Do you have a different Python interpreter set in

    Preferences > Python intrepreter

?

**Comment by colinww** [comment]
Hello,
When I run with the setting to `default`, spyder 4 starts up with:
```
Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
Type "copyright", "credits" or "license" for more information.

IPython 7.9.0 -- An enhanced Interactive Python.
```
I have a hard time understanding where this is coming from. I tried to trace the executable first in spyder:
```
import sys

sys.executable
Out[2]: '/Users/colinww/anaconda3/envs/spyder-beta/bin/python'
```
Then I followed this path in my terminal:
```
colinww@cambp ~ % ls -l /Users/colinww/anaconda3/envs/spyder-beta/bin/python
lrwxr-xr-x  1 colinww  staff  9 Nov 21 06:34 /Users/colinww/anaconda3/envs/spyder-beta/bin/python -> python3.7
colinww@cambp ~ % which python3.7
/Users/colinww/anaconda3/envs/spyder-beta/bin/python3.7
colinww@cambp ~ % ls -l /Users/colinww/anaconda3/envs/spyder-beta/bin/python3.7
-rwxrwxr-x  3 colinww  staff  4183940 Oct 25 08:57 /Users/colinww/anaconda3/envs/spyder-beta/bin/python3.7
colinww@cambp ~ % /Users/colinww/anaconda3/envs/spyder-beta/bin/python3.7
Python 3.7.5 (default, Oct 25 2019, 10:52:18)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
colinww@cambp ~ % /usr/bin/python3
Python 3.7.3 (default, Oct 11 2019, 19:39:43)
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
So I can't find where I have Python 3.7. (The apple version is 3.7.5 as shown).  Nevertheless, version 3.7 isn't the end of the world, so I try to run my scripts and I get:
```
runfile('/Users/colinww/system-model/work/fft_block_lms_noise_analysis.py', wdir='/Users/colinww/system-model/work', current_namespace=True)
Traceback (most recent call last):

  File "/Users/colinww/system-model/work/fft_block_lms_noise_analysis.py", line 13, in <module>
    import numpy as np

ModuleNotFoundError: No module named 'numpy'
```
To fix this, I explicitly specified the interpreter in the preferences: `/Users/colinww/anaconda3/bin/python3.7`

And now I run into the problem I originally posted.

By the way thank you for all you do for Spyder, all of us at our work love it.

**Comment by ccordoba12** [comment]
> To fix this, I explicitly specified the interpreter in the preferences: /Users/colinww/anaconda3/bin/python3.7
>
> And now I run into the problem I originally posted.

You need to update your spyder-kernels version installed for that Python interpreter. That's the solution to your problem.

> By the way thank you for all you do for Spyder, all of us at our work love it

Thanks a lot for your kind words!

**Comment by colinww** [comment]
> You need to update your spyder-kernels version installed for that Python interpreter. That's the solution to your problem.

I think I already have the latest version of spyder-kernels version installed, or at least the correct compatible version? I ran this already:
```
colinww@cambp system-model % conda update -n spyder-beta -c spyder-ide --all
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
Now this is the result of listing packages:
```
colinww@cambp system-model % conda list -n spyder-beta | grep spyder
# packages in environment at /Users/colinww/anaconda3/envs/spyder-beta:
applaunchservices         0.2.1                      py_0    spyder-ide
argh                      0.26.2                py37_1001    spyder-ide
diff-match-patch          20181111                   py_0    spyder-ide
jedi                      0.14.1                   py37_0    spyder-ide
pathtools                 0.1.2                      py_1    spyder-ide
pympler                   0.7                        py_0    spyder-ide
python-jsonrpc-server     0.3.0                      py_0    spyder-ide
python-language-server    0.31.1                   py37_0    spyder-ide
pyxdg                     0.26                       py_0    spyder-ide
qdarkstyle                2.7                        py_0    spyder-ide
qtconsole                 4.6.0                      py_0    spyder-ide
spyder                    4.0.0rc2                 py37_0    spyder-ide
spyder-kernels            1.8.0                    py37_0    spyder-ide
watchdog                  0.9.0                    py37_1    spyder-ide
```
It looks like the spyder-kernels are aligned to 10th place decimal versions of python. Also, there are two different "builds" depending on the channel, but both are aligned with python 3.7 it seems:
```
colinww@cambp system-model % conda search spyder-kernels
spyder-kernels                 1.4.0          py37_0  pkgs/main
```
and also
```
colinww@cambp system-model % conda search -c spyder-ide spyder-kernels
spyder-kernels                 1.8.0          py37_0  spyder-ide
```

Since my spyder version is on the `spyder-ide` channel, I feel like my version is aligned. Sorry if I am not understanding the correct update method.

**Comment by ccordoba12** [comment]
You're confusing two envs:

1. Your base env, which is at `/Users/colinww/anaconda3/bin/python3.7`. That's the env you set in our preferences, at least according to what you said at the end of https://github.com/spyder-ide/spyder-kernels/issues/184#issuecomment-557182454.
2. The env called `spyder-beta`, which is at `/Users/colinww/anaconda3/envs/spyder-beta`. It's in that env that you have the latest version of spyder-kernels, as reported in https://github.com/spyder-ide/spyder-kernels/issues/184#issuecomment-557331078.

So it seems you have an older version of `spyder-kernels` in your base env, and that's the one you need to update. Or you need to change the interpreter you're using in our Preferences to point to the Python executable present in your `spyder-beta` env.

**Comment by colinww** [comment]
Ok I am beginning to understand. I reverted my Spyder4 Python Interpreter to "Default", and restarted. Everything seems consistent except this:
![Screen Shot 2019-11-22 at 8 23 14 AM](https://user-images.githubusercontent.com/3949962/69442506-8e322200-0d01-11ea-8d39-200280a364e3.png)

At the bottom bar it shows I am in the spyder-beta environment (dash becomes underscore?), which is correct. It also shows that version of Python as 3.7.5, which is correct. And, the result of `sys.version_info` is consistent with this. So what threw me is the line `Python 3.7.0 (default, Jun 28 2018, 07:39:16)`.

Now, when I explicitly set the Python Interpreter to `/Users/colinww/anaconda3/envs/spyder-beta/bin/python` (which IS the default python in this spyder env), now I get:
![Screen Shot 2019-11-22 at 8 28 23 AM](https://user-images.githubusercontent.com/3949962/69442812-144e6880-0d02-11ea-8273-9756b5fb0600.png)
So my confusion is what is the relevance/meaning of that initial banner announcement? Functionally, it all seems to work so it's not terribly important but I would like to understand what is going on if possible. Thank you again.

**Comment by ccordoba12** [comment]
This looks like a bug, but I don't understand your setup very well nor how you fixed things. If you manage to describe in a simple way how that error appears, please report it [here](https://github.com/spyder-ide/spyder/issues).
