### ISSUE TITLE
saved session data scrambled(Save data as)

### ISSUE THREAD

**Issue by alessandroabr** [spyder-ide/spyder-kernels#203]
* [x] Searched 
* [x] Read
* [x] Reproduced the issue
* [ ] Could not reproduce 
* [ x] Tried basic troubleshooting 
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
"save data as" in the variable explorer scrambled all the lists in my SPYDERDATA file. I have lists of array that are my data and indices of events related to those data (EEG experiment). I can see they are scrambled from the length of the arrays (array 3 in list A should have the same length of array 3 in lists B and C , which is not the case)..

The first one or two arrays of each list  (of 3200 arrays) seem to be in the right place

Every time i reopen the file i get different lists of the same arrays, in other words the order of the arrays is changed.

Is there any way to recover the original structure of my data?

Thank you in advance. 

## Versions

* Spyder version: 3.3.1
* Python version: 3.5.2 64
* Qt version: 5.6.2
* PyQt version: 5 5.6
* Operating System name/version: windows 10

### Dependencies

```
IPython >=4.0     :  5.1.0 (OK)
cython >=0.21     :  0.24.1 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
matplotlib >=2.0.0:  1.5.3 (NOK)
nbconvert >=4.0   :  4.2.0 (OK)
numpy >=1.7       :  1.11.3 (OK)
pandas >=0.13.1   :  0.18.1 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  1.3.0 (OK)
pygments >=2.0    :  2.1.3 (OK)
pylint >=0.25     :  1.5.4 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
rope >=0.9.4      :  0.9.4-1 (OK)
sphinx >=0.6.6    :  1.4.6 (OK)
sympy >=0.7.3     :  1.0 (OK)
```

**Comment by ccordoba12** [comment]
> Is there any way to recover the original structure of my data?

I don't think so. And if you'd like to see this fixed in the future, please give us a simple, reproducible code that generates this problem.

**Comment by alessandroabr** [comment]
> > Is there any way to recover the original structure of my data?
> 
> I don't think so. And if you'd like to see this fixed in the future, please give us a simple, reproducible code that generates this problem.

here:
import numpy as np

gg=[np.zeros((1,25000)), np.ones((1,12000)), np.zeros((1,18000)), np.ones((1,30000)), np.zeros((1,20000))]

save using "save data as", then open again. the order of the arrays will be scrambled.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one to see if you can reproduce it.

**Comment by dalthviz** [comment]
@ccordoba12 I couldn't replicate this using Spyder 3.3.6 and 4.0.1 @alessandroabr could you try to update Spyder (seems like you are using Spyder 3.3.1) and see if you notice the same behavior?
