### ISSUE TITLE
double declaration of ipykernel causes poetry to fail

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder-kernels#210]
I tried to manage project using poetry
https://python-poetry.org
double declaration of `ipykernel` causes poetry to fail https://github.com/python-poetry/poetry/issues/2133

```
REQUIREMENTS = [
  ...
    'ipykernel',
    'ipykernel>=5.1.3; python_version>"2"',
  ...
]
```

After removing one of the dependcies ` poetry` could  install all packages.

**Comment by ccordoba12** [comment]
If pip can handle this correctly, I think this needs to be solved in Poetry and not here.
