### ISSUE TITLE
Display size of string in variable editor

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder-kernels#245]
Currently the variable explorer displays all strings with size `1` - I think it would be more intuitive to show the length of the string.

It would simply requiring to change the size here to include `str`

https://github.com/spyder-ide/spyder-kernels/blob/87d89ad94becb51f4eea1bea643334fd02440d6c/spyder_kernels/utils/nsview.py#L124

**Comment by ccordoba12** [comment]
Nice suggestion @skjerns! Please ahead for it.
