### ISSUE TITLE
Remove from warning that future versions of Spyder will give an error when using non-Python syntax

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-kernels#247]
Currently we're showing this warning

![immagine](https://user-images.githubusercontent.com/13431660/92300753-ae179700-ef5d-11ea-9cab-238a2f29c773.png)

I think we should remove its last sentence and perhaps reword its last part. That's because it seems a lot of people depends on this feature and forcing them to use `ipy` files would be a nuisance.

@impact27, what do you think?

**Comment by impact27** [comment]
"We recommand that you save this file with the .ipy extension."?

**Comment by ccordoba12** [comment]
I agree, that's a good suggestion.
