### ISSUE TITLE
Pyqtgraph does not work with Spyder

### ISSUE THREAD

**Issue by MohamadZohoori** [spyder-ide/spyder-kernels#283]
Hi, 

I tried to to run a very simple code with pyqtgraph like below:

import pyqtgraph 

xVals = [1,2,3,4,5]
yVals = [2,4,6,7,10]
pw = pyqtgraph.plot(xVals, yVals, pen='r')

And I faced this ERROR:

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\Qt.py", line 209, in <module>
    from PyQt5 import QtOpenGL

ValueError: PyCapsule_GetPointer called with incorrect name

How can I solve this?

Thanks in advance for your help.

**Comment by ccordoba12** [comment]
Hey @MohamadZohoori, thanks for reporting. That usually means an installation error with PyQt (probably because you installed it or Pyqtgraph with pip).

Unfortunately we can't help you with that here, sorry.
