### ISSUE TITLE
Support decorator >= 5

### ISSUE THREAD

**Issue by cbrnr** [spyder-ide/spyder-kernels#288]
Currently, `spyder-kernels` requires `decorator<5`. Now that the latest version of `decorator` is 5.0.7, this restriction should be bumped. I just tested it and everything seems to work just fine.

**Comment by ccordoba12** [comment]
That decorator version broke the Cython magic. Is that already fixed?

**Comment by cbrnr** [comment]
Not sure how to test this, but `%load_ext Cython` and `%%cython` seem to work just fine for me.

**Comment by cbrnr** [comment]
Seems to fixed.

**Comment by ccordoba12** [comment]
Nop, it's not. We still have to remove this constraint.

**Comment by cbrnr** [comment]
Sorry, my bad. I thought I'd updated `decorator` but I hadn't.

**Comment by MayeulC** [comment]
This broke spyder for me on Archlinux, which typically has newer package versions than other distributions. I guess we iron out bugs for other users sometimes...

Anyway, some missing functionality or a warning is preferable to me than no functionality.

**Comment by ccordoba12** [comment]
That's why you should use Spyder through Anaconda or pip. I'm pretty sure the Spyder that comes with Linux distros is broken in a lot of ways.

**Comment by cbrnr** [comment]
Thanks @ccordoba12 for fixing this issue! @MayeulC with this change it should work on Arch Linux again.

**Comment by MayeulC** [comment]
thanks a lot, it should trickle down the repositories quite soon as the package has been flagged out of date: https://archlinux.org/packages/community/any/python-spyder-kernels/

Out of curiosity @ccordoba12, why completely remove decorator from the requirements, instead of just the version number?

**Comment by ccordoba12** [comment]
> why completely remove decorator from the requirements, instead of just the version number?

Because it's a third-party dependency (it's an IPython dep really, we don't use it directly here). And, as far as I recall, it hadn't given problems before.

It's just that we needed to release Spyder 5.0.0 on April 2nd, so we couldn't wait until the decorator maintainer fixed some issues that appeared in it's 5.0 release.

**Comment by MayeulC** [comment]
Ah, that makes sense, thank you :+1:
