### ISSUE TITLE
Add option to use custom Outstream in kernel app

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder-kernels#302]
Using a custom Outstream allows us to set the `isatty` option that was introduced in https://github.com/ipython/ipykernel/pull/683. Setting the `isatty` to `True` allows packages like `rich` and `colorama` to have colored output in Spyder.

Also see https://github.com/jupyter/qtconsole/issues/486

@ccordoba12

**Comment by peendebak** [comment]
@ccordoba12 I looked into the code of `spyder-kernels`, but could not find where the `Outstream` is constructed. Could you give a pointer?

**Comment by eendebakpt** [comment]
@ccordoba12 Could it be that the `OutStream` is created here: https://github.com/ipython/ipykernel/blob/36d6a91639b3ec09502b5454d30751ad81ffab27/ipykernel/inprocess/ipkernel.py#L155 ?

In that case we would require another PR to `ipykernel` to allow setting the `isatty` option

**Comment by real-yfprojects** [comment]
In this [message](https://github.com/jupyter/qtconsole/issues/486#issuecomment-858807941) @ccordoba12 pointed to the `kernelapp.IPKernelApp` class. I think the `Outstream` instance is created here:

https://github.com/ipython/ipykernel/blob/7ed57cb4a03e719074c373029cf9f2e6dfd2c6de/ipykernel/kernelapp.py#L421

Here the `DottedObjectName` in `outsream_class` is imported and then used as `sys.stdout`.

**Comment by eendebakpt** [comment]
@real-yfprojects @ccordoba12 Thanks for the hint. There are various ways to make sure spyder uses a different `Outstream` class. I opted for one without any changes to the upstream `ipykernel` and one with minimal patching of the original `SpyderKernelApp`. Could you have a look at #305
