### ISSUE TITLE
formatargspec is deprecated since Python 3.5

### ISSUE THREAD

**Issue by mwtoews** [spyder-ide/spyder-kernels#307]
While using spyder 4.2.5 from conda-forge, I get the message:
> `dochelpers.py`:125: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly

The documentation for [`inspect.formatargspec`](https://docs.python.org/3/library/inspect.html#inspect.formatargspec) reflects this warning.

The relevant code to potentially refactor is: https://github.com/spyder-ide/spyder-kernels/blob/7cbd99673a03dc732041c1d3fad7795c1b683b58/spyder_kernels/utils/dochelpers.py#L116-L130

If Python 3.5 is no longer supported here, then hopefully it'll be straight-forward to do. Otherwise, a third block would be need to handle Python <3.5 and >=3.5 versions.

**Comment by spchamp** [comment]
It looks like this [might be addressed](https://github.com/spyder-ide/spyder-kernels/blob/master/spyder_kernels/utils/dochelpers.py#L112-L120) in the master branch now?

Albeit, somehow [the change](https://github.com/spyder-ide/spyder-kernels/commit/81193fcf74193e579e49f9eb927b8952ded92034) (from 26 November, 2021) does not seem to be present [in the 2.4.0 release](https://github.com/spyder-ide/spyder-kernels/blob/0d04badd374f1e82317aff97bd86a0baf4ba5f3c/spyder_kernels/utils/dochelpers.py#L116-L130) (from 2 November, 2022). 

I'd noticed this with Python 3.11, while testing some port updates on a  FreeBSD system. The older form doesn't seem to work out with this Python build.

**Comment by juliangilbey** [comment]
No, there's still no fix in 2.4.1.
