### ISSUE TITLE
do_inspect is failing with IPdb kernel

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-kernels#39]
Right is throwing an error every time a parenthesis is open in Qtconsole.

**Comment by dalthviz** [comment]
https://github.com/Calysto/metakernel/blob/967e803b0f69da73700fe7c014871b3c1eebe335/metakernel/_metakernel.py#L545

**Comment by ccordoba12** [comment]
@dalthviz, I think we need to solve things in our side here:

https://github.com/spyder-ide/spyder-kernels/blob/ipdb/spyder_kernels/ipdb/kernel.py#L169

or maybe here

https://github.com/spyder-ide/spyder-kernels/blob/ipdb/spyder_kernels/ipdb/kernel.py#L165
