### ISSUE TITLE
bdb.BdbQuit exception when i input 'q'  to exit ipdb

### ISSUE THREAD

**Issue by Mingming-a** [spyder-ide/spyder-kernels#393]
I use multi-threads for my work in spyder, i set breakpoint() in my thread, when IDE hit breakpoint i can use ipdb to debug my code. bdb.BdbQuit exception when i input 'q'  to exit ipdb. Here is a piece of code.
def invoke_master(mq, sq):
    try:
        print('******run master process******')        
        # 1. Instantiate CVB device.  tx
        chip_rx = sq.get()
        breakpoint()
        MYTRIMS0 = 'chip_master.csv'
        brd_tx, chip_tx = startup.cvb_chip_init(usb_dev_num=0, trim_data_file=MYTRIMS0)
        mq.put(chip_rx)
        print(f'******master end******')
    finally:
        pass

def invoke_slave(mq, sq):
    try:
        print('******run slave process******')
        # rx
        MYTRIMS1 = 'chip_slave.csv'        
        brd_rx, chip_rx = startup.cvb_chip_init(usb_dev_num=1, trim_data_file=MYTRIMS1)
        sq.put(chip_rx)  
        print(f'******slave wait******')
        chip_tx = mq.get()
        print(f'******slave end******')
    finally:
        pass
    

if __name__ == '__main__':
    t0 = time.time()
    print(f'main time is {t0}')
    coresNum = int(mp.cpu_count())
    print(f'cpu core num is {coresNum}')
    mq = Queue()
    sq = Queue()
    master=threading.Thread(target=invoke_master, args=(mq,sq,))
    slave=threading.Thread(target=invoke_slave, args=(mq,sq,))
    master.start()
    slave.start()
    master.join()
    slave.join()
    t1 = time.time()
    print(f'all tasks completed took time={t1 - t0:.2f}s...')

Here is the exception info
ipdb> q
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\songm\.conda\envs\labtest\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\songm\.conda\envs\labtest\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Git\python\labtest\projects\sei\a0\work\debug_multithread.py", line 61, in invoke_master
    MYTRIMS0 = 'chip_master.csv'
  File "D:\Git\python\labtest\projects\sei\a0\work\debug_multithread.py", line 61, in invoke_master
    MYTRIMS0 = 'chip_master.csv'
  File "C:\Users\songm\.conda\envs\labtest\lib\bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "C:\Users\songm\.conda\envs\labtest\lib\bdb.py", line 112, in dispatch_line
    self.user_line(frame)
bdb.BdbQuit

**Comment by ccordoba12** [comment]
Closing because this is not an issue anymore, unless you're using a very old Spyder version, which we don't support anymore.
