### ISSUE TITLE
Unable to start kernel due ModuleNotFoundError

### ISSUE THREAD

**Issue by Hui-Se** [spyder-ide/spyder-kernels#402]
Using `conda install spyder-kernels` and then running it `python -m spyder_kernels.console` . It shows 
`(base) [zhangyl@server miniconda3]$ python -m spyder-kernels.console
/mnt/public1/zhangyl/miniconda3/bin/python: Error while finding module specification for 'spyder-kernels.console' (ModuleNotFoundError: No module named 'spyder-kernels')
`
But it has already installed successfully.

> 

\# packages in environment at /mnt/public1/zhangyl/miniconda3:
\#
\# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2022.07.19           h06a4308_0    defaults
certifi                   2022.6.15        py39h06a4308_0    defaults
cffi                      1.15.0           py39hd667e15_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
cloudpickle               2.1.0                    pypi_0    pypi
conda                     4.13.0           py39h06a4308_0    defaults
conda-package-handling    1.8.1            py39h7f8727e_0    defaults
cryptography              37.0.1           py39h9ce1e76_0    defaults
debugpy                   1.6.2                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0    defaults
entrypoints               0.4              py39h06a4308_0    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          h06a4308_3561    defaults
ipykernel                 6.15.1                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
jedi                      0.18.1           py39h06a4308_1    defaults
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyter_client            7.2.2            py39h06a4308_0    defaults
jupyter_core              4.10.0           py39h06a4308_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgfortran-ng            7.5.0               ha8ba4b0_17    defaults
libgfortran4              7.5.0               ha8ba4b0_17    defaults
libgomp                   11.2.0               h1234567_1    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
matplotlib-inline         0.1.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py39h7f8727e_0    defaults
mkl_fft                   1.3.1            py39hd3c417c_0    defaults
mkl_random                1.2.2            py39h51133e4_0    defaults
ncurses                   6.3                  h5eee18b_3    defaults
nest-asyncio              1.5.5            py39h06a4308_0    defaults
numpy                     1.22.3           py39he7a7128_0    defaults
numpy-base                1.22.3           py39hf524024_0    defaults
openssl                   1.1.1q               h7f8727e_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pip                       22.1.2           py39h06a4308_0    defaults
prompt-toolkit            3.0.30                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.12.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.12               h12debd9_0    https://repo.anaconda.com/pkgs/main
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pyzmq                     23.2.0           py39h6a678d5_0    defaults
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.28.1           py39h06a4308_0    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
scipy                     1.7.3            py39hc147768_0    defaults
setuptools                61.2.0           py39h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
**spyder-kernels            2.2.1            py39h06a4308_0    defaults**
sqlite                    3.38.5               hc218d9a_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.0           py39h06a4308_0    defaults
traitlets                 5.3.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0    defaults
urllib3                   1.26.9           py39h06a4308_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
wurlitzer                 3.0.2            py39h06a4308_0    defaults
xz                        5.2.5                h7f8727e_1    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zeromq                    4.3.4                h2531618_0    defaults
zlib                      1.2.12               h7f8727e_2    defaults

> 

I do not know why it can not been searched.

**Comment by ccordoba12** [comment]
Hey @Hui-Se, thanks for reporting. The command you're running is

    python -m spyder-kernels.console

but the one you need to run to start a Spyder kernel is

    python -m spyder_kernels.console

(notice the underscore instead of the hyphen). I think that's the source of your problem.

So please do that and let us know if it works for you.

**Comment by Hui-Se** [comment]
@ccordoba12 
> but the one you need to run to start a Spyder kernel is
> 
> ```
> python -m spyder_kernels.console
> ```
> 

Yes, it works! How silly I am!!! 
Anyway, thanks a lot!!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about that.
