### ISSUE TITLE
Python 2 tests are broken in Conda slots

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder-kernels#405]
```
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/bin/pytest", line 11, in <module>
    sys.exit(main())
TypeError: 'NoneType' object is not callable
```

**Comment by impact27** [comment]
Works on `Linux pip tests` but not on `Linux tests` and `Macos tests`

**Comment by ccordoba12** [comment]
I think we shouldn't spend much time to keep our Python 2 support alive. So, please remove the slots for Python 2 in `Linux tests` and `Macos tests`. That way at least we'll continue to test Python 2 with Pip packages, which seems reliable so far.

You can do that as part of PR #404 or in a separate PR. It's up to you.
