### ISSUE TITLE
v2.3.3 still imports from distutils

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder-kernels#410]
In version 2.3.3, spyder_kernels still imports LooseVersion from distutils, which will soon be removed from Python:
https://github.com/spyder-ide/spyder-kernels/blob/3438148b2ce8139969b68bd99194c2083dcfb370/spyder_kernels/console/kernel.py#L14
The master branch no longer (?) has this import; perhaps whatever change was made there could be backported to 2.x?

**Comment by ccordoba12** [comment]
The thing is Spyder-kernels 2 still supports Python 2, and we're not going to change it on that branch. The future Spyder-kernels 3 will be Python 3 only, which allowed us to remove support for distutils.

Besides, distutils will be removed in Python 3.12, to be released next year. By that time, we expect to have released Spyder 6, which will depend on Spyder-kernels 3+.

**Comment by ccordoba12** [comment]
Closing because we're not going to do anything about this.
