### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by PEE8** [spyder-ide/spyder-kernels#43]
when does typeError comes as following:
raise TypeError("Cannot convert value %r to a TensorFlow DType." % type_value)

TypeError: Cannot convert value 'int' to a TensorFlow DType.

what are the parameters for getmodel()-in python 3.7 ?
Please let me know ... Thanks in advance

**Comment by ccordoba12** [comment]
Please don't report more errors about this. This is clearly not a problem in Spyder but in your code.
