### ISSUE TITLE
distutils and LooseVersion deprecation

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder-kernels#440]
As seen in the warning messages in #342, `distutils` is also being deprecated.  It is used in two places in `spyder_kernels`: `spyder_kernels/console/kernel.py` line 14 and `spyder_kernels/console/start.py` line 14, in both cases to import `LooseVersion`. Please could you replace this by something that doesn't require `distutils` before Python 3.12 comes out?

Thanks!

**Comment by ccordoba12** [comment]
Ok, although this is fixed in master we'll try to also fix it in 2.4.3 to avoid issues when Python 3.12 is released.
