### ISSUE TITLE
Codecov Package was Yanked

### ISSUE THREAD

**Issue by blink1073** [spyder-ide/spyder-kernels#454]
Downstream tests are [failing](https://github.com/ipython/ipykernel/actions/runs/4703224964/jobs/8341460682?pr=1110) because `spyder-kernels` has a dependency on  the `codecov` package, which is now defunct.

You can either use the codecov upload action, or use the new helper actions from maintainer-tools.  See https://github.com/ipython/ipykernel/pull/1109 for an example.

**Comment by ccordoba12** [comment]
Thanks @blink1073 for opening this issue. I'll fix it right away.
