### ISSUE TITLE
Tests missing on PyPI repository

### ISSUE THREAD

**Issue by FlingeR** [spyder-ide/spyder-kernels#66]
Hi,
Is it possible to have the tests added to future versions of spyder-kernels on PyPI ?
They are missing in 0.3.0 at least.

Thanks.
Elias.

**Comment by ccordoba12** [comment]
We decided to remove them from our tarballs because setting up a development environment to run them is not easy and it's going to become much harder in the future.

Sorry, but you'll have to trust our CI setup or clone the git repo to have them.
