### ISSUE TITLE
Namespace serialization silently fails if any object is unserializable, e.g. a Python module

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder-kernels#75]
A user reported on Gitter that Spyder's namespace saving feature was silently failing in certain situations, and upon testing it, an easily reproducible was was attempting to serialize Python modules, which cannot be serialized and are rarely if ever desired to be in this case. To fix this, we should:

* Fix error messages not being printed by handling exceptions in the ``deepcopy()`` call properly
* Call deepcopy on each individual value rather than the whole dict/namespace, to prevent falling back to normal ``copy`` or nothing at all for everything if one object cannot be deepcopied (or serialized entirely)
* Skip serializing anything that is a Python module EDIT: Or a function/class, as they can only be loaded if they already exist in the environment (thus it serves little purpose to do so, other than the prevent the rest of the environment from being loaded)
* If an object produces an error on attempted serialization, skip it and generate a popup warning listing the objects not serialized rather than refusing to save the entire session and forcing users to manually figure out and delete problem ones

@ccordoba12 These changes fix a major bug in namespace serialization, can all be implemented purely in Spyder-Kernels without any Spyder-side changes; and all in a file that has no changes (and thus no chance of merge conflicts) between ``0.x`` and ``master``, so can this go in ``0.x``?

**Comment by CAM-Gerlach** [comment]
Sure, sounds fine with me. It would incorporate these improvements as well as the #9 bug fix, and would also avoid more reports of the very-annoying #59 as people upgrade ``ipykernel``.

By that do you mean PyQt 5.12, once that's out for AD? I know Ray's been working on it but I didn't know if it was coming sooner than Spyder 4.

**Comment by ccordoba12** [comment]
PyQt 5.12 will probably come before we release Spyder 4, so it's better to be prepared.

**Comment by ccordoba12** [comment]
Could you take of these two bugs? It seems you investigated quite well how to solve them.

**Comment by CAM-Gerlach** [comment]
Yep, already in progress although I need to pause it to finish up the DARPA proposal draft first.
