### ISSUE TITLE
Detect the name of the file currently running the cell

### ISSUE THREAD

**Issue by hmaarrfk** [spyder-ide/spyder-kernels#76]
I think it would be useful to obtain the name of the file currently running the cell.

__spyder_cell_file__

It would be nice if I could get to the point in my script, that would programmatically:
 * Save the current working file
 * Copy it to some known directory for archival purposes

Checking for the existance of the `__file__` is a little problematic, because it can be set by a `run` command, and it won't be unset.

The current working directory if often clobbered when restarting kernels and navigating through the file explorer.

XREF: https://stackoverflow.com/questions/54221512/get-name-of-file-where-the-cell-is-running-from-in-spyder/54224444#54224444

**Comment by ccordoba12** [comment]
@bcolsen, what do you think about this one?
