### ISSUE TITLE
Nopython jit of numba is not working in runcell

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder-kernels#78]
The nopython jit of numba is working well in runfile.

![runfile](https://user-images.githubusercontent.com/22970578/51612759-749b3f00-1f65-11e9-9f34-e78988e7fd8c.gif)

The nopython jit of numba is not working in runcell.

![runcell](https://user-images.githubusercontent.com/22970578/51612804-8aa8ff80-1f65-11e9-892d-bd213ddf8f15.gif)

[example.zip](https://github.com/spyder-ide/spyder-kernels/files/2787639/example.zip)

I hope this is not happening only on my computer.
And I hope my example will help your team.
If this issue is not related to this repository, I will move it to spyder repository.

## Versions

* Spyder version: spyder 4.0 dev lastest master [4166830](https://github.com/spyder-ide/spyder/commit/416683058aa126499b5777f00f12f644b5f67a48)
* Spyder-kernels version: 1.2.0
* Python version: 3.6.7
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: 4.20.1-1-MANJARO

IPython >=4.0     :  6.4.0 (OK)
cython >=0.21     :  0.28.2 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.16.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
numba               : 0.38.0

**Comment by ccordoba12** [comment]
@bcolsen, could you take a look at this one? Thanks!

**Comment by bcolsen** [comment]
I have a fix!! 

The problem is the `umr` deleting things when they aren't getting defined again.  I can also reproduce this with `runfile` by making a file that uses imports that are made in another file.  I don't think that's an issue because that shouldn't run in python any way.

IPython seems to do some magic here already with the `run_cell` code I'm using currently so the spyder `umr` should be unnecessary now.

**Comment by ccordoba12** [comment]
Thanks for the lighting fast respose @bcolsen!
